# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:3.3.9

pipelines:
  default:
    - step:
        caches:
          - maven
        script: # Modify the commands below to build your repository.
          - mvn clean install
        artifacts: # defining the artifacts to be passed to each future step.
          - jars/**
    - step:
        name: Uploading new file
        deployment: production   # can be test, staging or production.
        # trigger: manual  # Uncomment to make this a manual deployment.
        script:
          - pipe: atlassian/sftp-deploy:0.3.1
            variables:
              USER: 'root'
              SERVER: '23.94.53.246'
              REMOTE_PATH: '/home/bungee/plugins'
              LOCAL_PATH: 'jars/bungee-1.0-SNAPSHOT.jar'
          - echo "Attempted to upload"